### ISSUE TITLE
I want to see the assignee for each task so that I can find the ones that I'm assigned to

### ISSUE THREAD

**Issue by yunzhihuang93** [romaannaeem/project-analyzer#1]

**Comment by romaannaeem** [comment]
I can implement task searching instead of this? I think that would be better UX.

**Comment by romaannaeem** [comment]
Search bar has been implemented. You can check it out [here](https://project-analyzer.herokuapp.com/). This should solve the issue you were having, though in a slightly different way than suggested! For that reason I'm gonna close this issue. Feel free to re-open it if you feel the need to.
